#ifndef PKCS11_CRYPTOLIB_H
#define PKCS11_CRYPTOLIB_H


#include <stdint.h>
#include <string.h>

#define CK_PTR *
#define CK_DEFINE_FUNCTION(returnType, name) returnType name
#define CK_DECLARE_FUNCTION(returnType, name) returnType name
#define CK_DECLARE_FUNCTION_POINTER(returnType, name) returnType (* name)
#define CK_CALLBACK_FUNCTION(returnType, name) returnType (* name)

#ifndef NULL_PTR
#define NULL_PTR 0
#endif

#define IGNORE(P) (void)(P)

#define PKCS11_CRYPTOLIB_CK_INFO_MANUFACTURER_ID "InterGalaxy"
#define PKCS11_CRYPTOLIB_CK_INFO_LIBRARY_DESCRIPTION "PKCS#11 interface v2.40"
#define PKCS11_CRYPTOLIB_CK_INFO_LIBRARY_VERSION_MAJOR 0x02
#define PKCS11_CRYPTOLIB_CK_INFO_LIBRARY_VERSION_MINOR 0x38

#define PKCS11_CRYPTOLIB_CK_SLOT_ID 1
#define PKCS11_CRYPTOLIB_CK_SLOT_INFO_SLOT_DESCRIPTION "CryptoKey slot"
#define PKCS11_CRYPTOLIB_CK_SLOT_INFO_MANUFACTURER_ID "InterGalaxy"
#define PKCS11_CRYPTOLIB_CK_SESSION_ID 1

#define CKF_SO_PUK_INITIALIZED    0x00000010UL  /* normal user's PIN is set */

typedef enum
{
	PKCS11_CRYPTOLIB_CK_OPERATION_NONE,
	PKCS11_CRYPTOLIB_CK_OPERATION_FIND,
	PKCS11_CRYPTOLIB_CK_OPERATION_ENCRYPT,
	PKCS11_CRYPTOLIB_CK_OPERATION_DECRYPT,
	PKCS11_CRYPTOLIB_CK_OPERATION_DIGEST,
	PKCS11_CRYPTOLIB_CK_OPERATION_SIGN,
	PKCS11_CRYPTOLIB_CK_OPERATION_SIGN_RECOVER,
	PKCS11_CRYPTOLIB_CK_OPERATION_VERIFY,
	PKCS11_CRYPTOLIB_CK_OPERATION_VERIFY_RECOVER,
	PKCS11_CRYPTOLIB_CK_OPERATION_DIGEST_ENCRYPT,
	PKCS11_CRYPTOLIB_CK_OPERATION_DECRYPT_DIGEST,
	PKCS11_CRYPTOLIB_CK_OPERATION_SIGN_ENCRYPT,
	PKCS11_CRYPTOLIB_CK_OPERATION_DECRYPT_VERIFY
}
PKCS11_CRYPTOLIB_CK_OPERATION;

#include "pkcs11.h"

#endif /* PKCS11_CRYPTOLIB_H */